In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
1 + 1 

2

In [3]:
numpy

NameError: name 'numpy' is not defined

In [1]:
import numpy as np

In [2]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [4]:
a = np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [6]:
type(a)

numpy.ndarray

In [7]:
print(a+a)

[2 4 6]


In [8]:
a = np.random.rand(5000)

In [9]:
np.sum(a)

2495.7347016905765

In [10]:
sum(a)

2495.7347016905765

In [11]:
a = np.array([4, 9, 10])

In [12]:
b = np.array([8, 12, 15])

In [13]:
np.sum(a, b)

TypeError: only integer scalar arrays can be converted to a scalar index

In [14]:
print(a+b)

[12 21 25]


In [15]:
print(a*b)

[ 32 108 150]


In [16]:
np.sum(a)/len(a)

7.666666666666667

In [17]:
np.mean(a)

7.666666666666667

In [18]:
a.sum()

23

In [19]:
mean = np.sum(a)/len(a)

In [23]:
variance_a = [map(lambda x: (x-mean)**2, a)]

In [26]:
variance = np.sum(variance_a)/len(variance_a)

TypeError: unsupported operand type(s) for /: 'map' and 'int'

In [24]:
print(variance_a)

In [25]:
print(a)

[ 4  9 10]


In [27]:
c = np.random.rand(128)

In [28]:
print(c)

[ 0.13405494  0.44480079  0.68080406  0.06489029  0.81072967  0.09431272
  0.08963298  0.66193803  0.95825762  0.48586333  0.64298465  0.31551621
  0.79047507  0.53023957  0.60474278  0.3392546   0.79347717  0.7217875
  0.66441313  0.419769    0.83128063  0.94490832  0.24149339  0.59526454
  0.00251515  0.14513402  0.06669293  0.18109211  0.95459382  0.37847927
  0.19599781  0.1233982   0.64663338  0.5790486   0.7625753   0.34054089
  0.25419575  0.87826482  0.85459099  0.47410273  0.84229301  0.63417025
  0.92869096  0.53586583  0.56903424  0.77490274  0.31456052  0.28805325
  0.6130103   0.47643415  0.31873206  0.82959393  0.81659149  0.71543775
  0.56548911  0.89519302  0.62690597  0.64283763  0.74594207  0.26764324
  0.24573933  0.69923693  0.7943777   0.10612781  0.92457049  0.83918071
  0.62518845  0.2233382   0.53887762  0.30600484  0.48491463  0.609116
  0.90434483  0.97369772  0.47563814  0.64661776  0.00711979  0.64677289
  0.43389216  0.64980086  0.0420241   0.07574278  0.02

In [29]:
print(np.sum(c))

66.8069779244


In [30]:
d = np.random.rand(1024,)

In [33]:
e = np.array(d[0:511])

In [34]:
print(e)

[ 0.38241788  0.28904865  0.24159544  0.19405858  0.88608675  0.74706286
  0.26714849  0.48718205  0.01375279  0.31114767  0.33269056  0.29088856
  0.5164818   0.87217625  0.25569061  0.63342502  0.86673682  0.5491733
  0.75818575  0.09204383  0.29787304  0.66944291  0.04893833  0.98594088
  0.15355062  0.41901976  0.01752771  0.57928742  0.80381121  0.01767144
  0.553508    0.58505519  0.78260506  0.00664968  0.26472986  0.18900544
  0.71068586  0.49204165  0.04898754  0.76417428  0.46816884  0.38473172
  0.67427058  0.28583128  0.19417164  0.09062929  0.68380993  0.8483667
  0.49733091  0.47152501  0.74247917  0.97100148  0.62058957  0.14532688
  0.34381968  0.43628233  0.98221152  0.23236334  0.91851944  0.22417388
  0.52271057  0.3215717   0.1658482   0.69973443  0.6503693   0.02928844
  0.52572515  0.39682351  0.97695314  0.85520926  0.99347034  0.66676911
  0.49597061  0.15148879  0.8625265   0.20511948  0.94041564  0.26997494
  0.06453498  0.16132664  0.4051253   0.09474067  0.9

In [35]:
print(d)

[ 0.38241788  0.28904865  0.24159544 ...,  0.47027372  0.63174635
  0.07237323]


In [36]:
len(d)

1024

In [37]:
print(d[0:511])

[ 0.38241788  0.28904865  0.24159544  0.19405858  0.88608675  0.74706286
  0.26714849  0.48718205  0.01375279  0.31114767  0.33269056  0.29088856
  0.5164818   0.87217625  0.25569061  0.63342502  0.86673682  0.5491733
  0.75818575  0.09204383  0.29787304  0.66944291  0.04893833  0.98594088
  0.15355062  0.41901976  0.01752771  0.57928742  0.80381121  0.01767144
  0.553508    0.58505519  0.78260506  0.00664968  0.26472986  0.18900544
  0.71068586  0.49204165  0.04898754  0.76417428  0.46816884  0.38473172
  0.67427058  0.28583128  0.19417164  0.09062929  0.68380993  0.8483667
  0.49733091  0.47152501  0.74247917  0.97100148  0.62058957  0.14532688
  0.34381968  0.43628233  0.98221152  0.23236334  0.91851944  0.22417388
  0.52271057  0.3215717   0.1658482   0.69973443  0.6503693   0.02928844
  0.52572515  0.39682351  0.97695314  0.85520926  0.99347034  0.66676911
  0.49597061  0.15148879  0.8625265   0.20511948  0.94041564  0.26997494
  0.06453498  0.16132664  0.4051253   0.09474067  0.9

In [38]:
shape(e)

(511,)

In [39]:
shape(d)

(1024,)

In [40]:
e = np.array(d[0:512])

In [41]:
shape(e)

(512,)

In [42]:
f = np.array(d[22:42])

In [45]:
g = np.random.randint(100, size=100)

In [46]:
print(g)

[35 42 77  3 21 48 16 17 35 80 53 94 41 79 36 28 24 65 82  0 85 33 12 72 33
 13 69 85 99 86 27 12 61 27 58  2 48 41 17 90 18 96 26 73 79 61 86 45 30 36
 56  9 24 77 88 61 59 36 63 27 49 89 36 45 46 21  0 21 39 42 41 76 39 21 75
  2 64 82 43 94 20 37 73 88 89 74 26  6 19 36 96 92 27 71 56 85 83 79 70  6]


In [49]:
h = np.array(d[g[0]]:d[g[-1]])

SyntaxError: invalid syntax (<ipython-input-49-f1c2fb21e156>, line 1)

In [48]:
print(h)

[]


In [50]:
d[g[0]]

0.1890054387001493

In [51]:
d[g[-1]]

0.26714848721956375

In [59]:
h = d[np.array(g[0:-1])]

In [54]:
d[np.array([35, 42, 77])]

array([ 0.18900544,  0.67427058,  0.26997494])

In [57]:
g[0:100]

array([35, 42, 77,  3, 21, 48, 16, 17, 35, 80, 53, 94, 41, 79, 36, 28, 24,
       65, 82,  0, 85, 33, 12, 72, 33, 13, 69, 85, 99, 86, 27, 12, 61, 27,
       58,  2, 48, 41, 17, 90, 18, 96, 26, 73, 79, 61, 86, 45, 30, 36, 56,
        9, 24, 77, 88, 61, 59, 36, 63, 27, 49, 89, 36, 45, 46, 21,  0, 21,
       39, 42, 41, 76, 39, 21, 75,  2, 64, 82, 43, 94, 20, 37, 73, 88, 89,
       74, 26,  6, 19, 36, 96, 92, 27, 71, 56, 85, 83, 79, 70,  6])

In [60]:
print(h)

[ 0.18900544  0.67427058  0.26997494  0.19405858  0.66944291  0.49733091
  0.86673682  0.5491733   0.18900544  0.4051253   0.14532688  0.29215314
  0.38473172  0.16132664  0.71068586  0.80381121  0.15355062  0.02928844
  0.9669663   0.38241788  0.42808881  0.00664968  0.5164818   0.49597061
  0.00664968  0.87217625  0.85520926  0.42808881  0.02822408  0.65892318
  0.57928742  0.5164818   0.3215717   0.57928742  0.91851944  0.24159544
  0.49733091  0.38473172  0.5491733   0.4671944   0.75818575  0.74901227
  0.01752771  0.15148879  0.16132664  0.3215717   0.65892318  0.09062929
  0.553508    0.71068586  0.98221152  0.31114767  0.15355062  0.26997494
  0.71654216  0.3215717   0.22417388  0.71068586  0.69973443  0.57928742
  0.47152501  0.89377997  0.71068586  0.09062929  0.68380993  0.66944291
  0.38241788  0.66944291  0.76417428  0.67427058  0.38473172  0.94041564
  0.76417428  0.66944291  0.20511948  0.24159544  0.6503693   0.9669663
  0.28583128  0.29215314  0.29787304  0.49204165  0.

In [61]:
i = np.random.rand(10,)

In [65]:
j = np.array(i[::-1])

In [63]:
print(i)

[ 0.95250843  0.17687312  0.78393675  0.28925246  0.10613189  0.6328285
  0.03600895  0.98376234  0.38832059  0.36002325]


In [66]:
print(j)

[ 0.36002325  0.38832059  0.98376234  0.03600895  0.6328285   0.10613189
  0.28925246  0.78393675  0.17687312  0.95250843]


In [67]:
k = np.random.rand(128,)

In [71]:
l = k[k<=0.5]

In [69]:
print(k)

[ 0.95237309  0.10367078  0.65295702  0.26712462  0.78214884  0.78220211
  0.4979168   0.22674851  0.71488111  0.59783817  0.00105499  0.43844824
  0.62339734  0.3479525   0.12504527  0.12542735  0.76881808  0.24994948
  0.36442469  0.93024177  0.18207698  0.9103648   0.43166029  0.09705805
  0.15012781  0.68916959  0.55396574  0.75564564  0.8786309   0.35211635
  0.24540265  0.19913626  0.56488488  0.57883205  0.72242133  0.33554074
  0.93182713  0.55774132  0.40647874  0.94436567  0.88202694  0.91574246
  0.86936033  0.57509211  0.79725274  0.70615523  0.23723642  0.20804119
  0.20965264  0.94159504  0.20150695  0.00386896  0.64470389  0.48626705
  0.8173711   0.22155599  0.15070542  0.74840058  0.36027987  0.98990651
  0.1179769   0.90328947  0.87548399  0.28863776  0.70662593  0.08021555
  0.53852888  0.69795403  0.97679059  0.52668008  0.46324332  0.59720604
  0.84565213  0.75117263  0.45947931  0.41546019  0.9920186   0.14628956
  0.01585688  0.10745399  0.24392293  0.96167181  0

In [72]:
print(l)

[ 0.10367078  0.26712462  0.4979168   0.22674851  0.00105499  0.43844824
  0.3479525   0.12504527  0.12542735  0.24994948  0.36442469  0.18207698
  0.43166029  0.09705805  0.15012781  0.35211635  0.24540265  0.19913626
  0.33554074  0.40647874  0.23723642  0.20804119  0.20965264  0.20150695
  0.00386896  0.48626705  0.22155599  0.15070542  0.36027987  0.1179769
  0.28863776  0.08021555  0.46324332  0.45947931  0.41546019  0.14628956
  0.01585688  0.10745399  0.24392293  0.13916646  0.14581632  0.16478802
  0.24501535  0.02192892  0.14719302  0.00957648  0.13650421  0.10563706
  0.14570116  0.27008425  0.16483906  0.36559185  0.2602263   0.03899158
  0.03900286  0.47862733  0.49355674  0.23173554  0.44573444  0.47046042
  0.094292    0.36933472  0.48318172  0.39053824  0.38250468  0.40170655
  0.37770482]


In [75]:
array = np.array([[8, 10 ,11, 12, 19], [9, 100, 9, 18, 1], [5, 12, 90,120, 34 ]])

In [76]:
print(array)

[[  8  10  11  12  19]
 [  9 100   9  18   1]
 [  5  12  90 120  34]]


In [77]:
arrayA = np.random.rand(12)

In [79]:
arrayB= arrayA.reshape(12, 1)

In [80]:
print(arrayA)

[ 0.42238105  0.80805148  0.47923504  0.48813892  0.86556844  0.48876263
  0.09507475  0.02558515  0.96737701  0.30277338  0.66040813  0.07583171]


In [81]:
print(arrayB)

[[ 0.42238105]
 [ 0.80805148]
 [ 0.47923504]
 [ 0.48813892]
 [ 0.86556844]
 [ 0.48876263]
 [ 0.09507475]
 [ 0.02558515]
 [ 0.96737701]
 [ 0.30277338]
 [ 0.66040813]
 [ 0.07583171]]


In [82]:
array2 = np.array([1, 0, 1, 0, 1])

In [86]:
array2_2 = np.tile(array2, (3,1))

In [87]:
print(array2_2)

[[1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]]


In [88]:
array1_2 = array + array2_2

In [89]:
print(array1_2)

[[  9  10  12  12  20]
 [ 10 100  10  18   2]
 [  6  12  91 120  35]]


In [91]:
mean1 = np.average(array[0])

In [92]:
mean1

12.0

In [93]:
mean2 = np.average(array[1])

In [94]:
mean2

27.399999999999999

In [100]:
array_mean1 = np.tile(mean1, (1,5))

In [101]:
print(array_mean1)

[[ 12.  12.  12.  12.  12.]]


In [102]:
array_subtract_mean1 = array[1] - array_mean1[0]

In [103]:
print(array_subtract_mean1)

[ -3.  88.  -3.   6. -11.]


In [104]:
print(array[1])

[  9 100   9  18   1]


In [105]:
inner_product = array @ array2

In [106]:
inner_product


array([ 38,  19, 129])

In [107]:
print(array)

[[  8  10  11  12  19]
 [  9 100   9  18   1]
 [  5  12  90 120  34]]


In [108]:
print(array2)

[1 0 1 0 1]


In [109]:
print(inner_product
     )

[ 38  19 129]


In [110]:
array3 = np.random.rand(3,5)

In [111]:
print(array3)

[[ 0.76418309  0.21968871  0.66984693  0.49128307  0.43930409]
 [ 0.82060503  0.36214902  0.72723412  0.07187377  0.59805459]
 [ 0.49781553  0.99971661  0.81858934  0.44255512  0.60914773]]


In [112]:
array4 = np.random.rand(4,)

In [113]:
print(array4)

[ 0.82489243  0.52545083  0.86055849  0.00564307]


In [114]:
array4T = np.transpose(array4)

In [115]:
print(array4T)

[ 0.82489243  0.52545083  0.86055849  0.00564307]


In [117]:
np.shape(array4)

(4,)

In [118]:
v3 = np.random.rand(3,)

In [119]:
v31 = v3.reshape(3,1)

In [120]:
v3 @ array3

array([ 1.1237919 ,  0.69268889,  1.11383356,  0.4214152 ,  0.84420002])

In [121]:
v31 @ array3

ValueError: shapes (3,1) and (3,5) not aligned: 1 (dim 1) != 3 (dim 0)

In [122]:
np.transpose(v31) @ array3

array([[ 1.1237919 ,  0.69268889,  1.11383356,  0.4214152 ,  0.84420002]])